<?php

namespace app\models;

use Yii;
use yii\web\UploadedFile;

/**
 * This is the model class for table "news".
 *
 * @property int $id
 * @property string $pic_path
 * @property string $text
 * @property string $header
 */
class News extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'news';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['pic_path', 'header'], 'string', 'max' => 32],
            [['text'], 'string', 'max' => 255],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'pic_path' => 'Pic Path',
            'text' => 'Text',
            'header' => 'Header',
        ];
    }


    public function saveImage($filename){

        $this->pic_path = $filename;

        //отключим валидацию
        return $this->save(false);
    }

    public function getImage(){

        if($this->pic_path){

            return '/web/uploads/'.$this->pic_path;

        }
        return '/web/uploads/no_foto.jpg';
    }

    public function deleteImage()
    {
        $imageUploadModel = new ImageUpload();
        $imageUploadModel->deleteCurrentImage($this->pic_path);
    }

    public function beforeDelete()
    {
        $this->deleteImage();
        return parent::beforeDelete(); // TODO: Change the autogenerated stub
    }
}
